# Generated by Django 5.1.2 on 2024-10-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.IntegerField()),
                ('tue', models.IntegerField()),
                ('wed', models.IntegerField()),
                ('thu', models.IntegerField()),
                ('fri', models.IntegerField()),
                ('sat', models.IntegerField()),
                ('sun', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Monday',
        ),
    ]
